version: '3.8'

services:
  frontend:
    container_name: booking-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    networks:
      - frontend
    deploy:
      resources:
        limits:
          memory: '1024M'
        reservations:
          memory: '0'

networks:
  frontend:
    name: booking_booking
    external: true
